---
title: "Untitled"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(ggplot2)
```

```{r}
a<-read.table("C:\\Users\\jiewei feng\\Desktop\\R\\data1.txt",header =TRUE,na.strings =".")
###delete the variables that does not change
b<-matrix(unlist(a),1721,116)
d<-b[,c(2:115)]
c<-as.data.frame(colSums(d*d))
c1<-as.data.frame(c(1:114))
c2<-as.data.frame(c(c,c1))
library(dplyr)
c3<-filter(c2,c2[,1]==0)
b1<-b[,-(c3[,2]+1)]

```
### linear regression
```{r}

b2<-as.data.frame(b1)
b2<-b2[,c(2:115)]
linear<-lm(b2$V115 ~ ., data=b2)
summary(linear)

```
The result says 'Coefficients: (1 not defined because of singularities)'.Which is reasonable because there are 114 heros in total, one we know is not available,if we know if each of the other 112 heros are selected or not , we know if the 114th hero is selected.
So we remove the last hero variable.

```{r}

b3<-as.data.frame(b2)
b3<-b3[,c(1:112,114)]
linear<-lm(b3$V115 ~ ., data=b3)
summary(linear)

```

```{r}
predict(linear,b3[c(1:100),c(1:113),])

```




###logistic

```{r}

logistic<-glm(b3$V115 ~ ., data=b3, family=binomial(link='logit'))
summary(logistic)

```
```{r}
r<-predict(logistic,,type='response',newdata=b3[c(1:1721),c(1:112),])

```

```{r}
r<-as.data.frame(r)
r1<-b3[,113]
r2<-cbind(r1,r)
r3<-filter(r2,r<0.2)
r4<-filter(r2,r>0.8)
r5<-rbind(r3,r4)
r6<-as.data.frame(abs(r5[,1]-r5[,2]))
names(r6)[1]<-c("dif")
r6<-filter(r6,dif<=0.5)
```







```{r}
b4<-b3[1,c(1:112)]
b4<-as.data.frame(t(b4))
b41<-cbind(b4,c(1:112))
b42<-filter(b41,b41[,1]!=0)
b5<-b3[1,c(1:112)]
b5[1,4]<-0
```

```{r}
b6<-as.data.frame(c(1:104))
b7<-merge(b5,b6)
t0<-as.data.frame(c(1:104)+9)
```

```{r}
n<-1
for (i in 1:103){
  m<-1
  while (m==1){
    if(sum(b7[,n])==0){
      b7[i,n]<-1
      m<-0
      t0[i,1]<-n
    } else{
      n<-n+1
    }
  }
}
```

```{r}
o1<-predict(logistic,,type='response',newdata=b7)
o2<-as.data.frame(o1)
o3<-cbind(o2,t0)
o4<-filter(o3,o1==max(o2))
if(o4[1,2]>23){
  o4[1,2]<-o4[1,2]+1
}
names(o4)[1:2]<-c("probability","hero")
o4[1,]
```



